export enum BenefitErrorCode {
  UNAVAILABLE = 'BENEFIT_UNAVAILABLE',
  NOT_FOUND = 'BENEFIT_NOT_FOUND',
  AMAZON_TOKEN_MISSING = 'AMAZON_TOKEN_MISSING',
  UNKNOWN = 'UNKNOWN_ERROR',
  EXPIRED = 'BENEFIT_EXPIRED'
}
