import { Collectible } from 'types/Collectible'
import { zeroIfNull } from './zero-if-null'

export const isSoldOut = (collectible: Collectible) : boolean => {
  const areCodesAvailable = zeroIfNull(collectible.available_codes) > 0
  const isAutoGeneratedCodeAvailable = (collectible.auto_generate_claim_code
        && (zeroIfNull(collectible.claimed_count) < zeroIfNull(collectible.total_count)))

  return !areCodesAvailable && !isAutoGeneratedCodeAvailable
}

export const getAvailableCodes = (collectible?: Collectible) : number => (
  collectible?.auto_generate_claim_code
    ? zeroIfNull(collectible?.total_count) - zeroIfNull(collectible?.claimed_count)
    : zeroIfNull(collectible?.available_codes)
)
