import { Collectible } from 'types/Collectible'
import { zeroIfNull } from './zeroIfNull'

export const isSoldOut = (collectible: Collectible) : boolean => {
  const areCodesAvailable = zeroIfNull(collectible.available_codes) > 0
  const isAutoGeneratedCodeAvailable = (collectible.auto_generate_claim_code
        && (zeroIfNull(collectible.claimed_count) < zeroIfNull(collectible.total_count)))

  return !areCodesAvailable && !isAutoGeneratedCodeAvailable
}
